import { Template } from "../types/portfolio.ts";

export const templates: Template[] = [
  // Basic Templates
  {
    id: "simple",
    name: "Simple & Clean",
    description: "Clean white design perfect for beginners",
    difficulty: "simple",
    preview: "/templates/simple-preview.png",
  },
  {
    id: "minimal",
    name: "Minimalist",
    description: "Simple and elegant design with plenty of whitespace",
    difficulty: "simple",
    preview: "/templates/minimal-preview.png",
  },
  {
    id: "professional",
    name: "Professional Dark",
    description: "Modern dark theme with purple gradients and mobile-first design",
    difficulty: "intermediate",
    preview: "/templates/professional-preview.png",
  },
  {
    id: "creative",
    name: "Creative Portfolio",
    description: "Bold design with unique layouts and animations",
    difficulty: "advanced",
    preview: "/templates/creative-preview.png",
  },
  
  // Developer-Specific Templates
  {
    id: "frontend",
    name: "Frontend Developer",
    description: "UI/UX focused template with modern design and responsive layouts",
    difficulty: "intermediate",
    preview: "/templates/frontend-preview.png",
  },
  {
    id: "backend",
    name: "Backend Developer",
    description: "Server-side focused template with API and database emphasis",
    difficulty: "intermediate",
    preview: "/templates/backend-preview.png",
  },
  {
    id: "fullstack",
    name: "Full Stack Developer",
    description: "Comprehensive template covering both frontend and backend technologies",
    difficulty: "intermediate",
    preview: "/templates/fullstack-preview.png",
  },
  {
    id: "mobile",
    name: "Mobile App Developer",
    description: "Specialized template for mobile app developers with React Native & Flutter focus",
    difficulty: "intermediate",
    preview: "/templates/mobile-preview.png",
  },
  {
    id: "devops",
    name: "DevOps Engineer",
    description: "Infrastructure and automation focused template with cloud technologies",
    difficulty: "advanced",
    preview: "/templates/devops-preview.png",
  },
  {
    id: "qa",
    name: "QA Engineer",
    description: "Testing and quality assurance focused template with automation tools",
    difficulty: "intermediate",
    preview: "/templates/qa-preview.png",
  },
  {
    id: "game",
    name: "Game Developer",
    description: "Game development focused template with Unity and Unreal Engine emphasis",
    difficulty: "advanced",
    preview: "/templates/game-preview.png",
  },
  {
    id: "data",
    name: "Data Engineer",
    description: "Data processing and analytics focused template with big data tools",
    difficulty: "advanced",
    preview: "/templates/data-preview.png",
  },
  {
    id: "aiml",
    name: "AI/ML Developer",
    description: "Artificial intelligence and machine learning focused template",
    difficulty: "advanced",
    preview: "/templates/aiml-preview.png",
  },
  {
    id: "cloud",
    name: "Cloud Engineer",
    description: "Cloud infrastructure and services focused template with AWS/Azure/GCP",
    difficulty: "advanced",
    preview: "/templates/cloud-preview.png",
  },
  {
    id: "security",
    name: "Security Developer",
    description: "Cybersecurity and secure development focused template",
    difficulty: "advanced",
    preview: "/templates/security-preview.png",
  },
  {
    id: "database",
    name: "Database Developer",
    description: "Database design and management focused template with SQL expertise",
    difficulty: "intermediate",
    preview: "/templates/database-preview.png",
  },
  {
    id: "blockchain",
    name: "Blockchain Developer",
    description: "Blockchain and cryptocurrency focused template with smart contracts",
    difficulty: "advanced",
    preview: "/templates/blockchain-preview.png",
  },
  {
    id: "system",
    name: "System Software Developer",
    description: "Operating systems and low-level programming focused template",
    difficulty: "advanced",
    preview: "/templates/system-preview.png",
  },
  {
    id: "embedded",
    name: "Embedded Systems Developer",
    description: "Hardware and embedded systems focused template with IoT emphasis",
    difficulty: "advanced",
    preview: "/templates/embedded-preview.png",
  },
];
